### ISSUE TITLE
Read file

### ISSUE THREAD

**Issue by aleksia123** [sonejostudios/LoopTool#1]
hi I tried running this but it gives me this error:

  File "./LoopTool.py", line 1233, in <module>
    my_gui = MainWindow(root)
  File "./LoopTool.py", line 83, in __init__
    self.logo = PhotoImage(file='bg.png')
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', 'imgtype', 'name') + options)
_tkinter.TclError: image type "imgtype" doesn't exist

**Comment by sonejostudios** [comment]
Hi @aleksia123 ,

what OS and what Python version are you using? Are you sure you have the latest sndfile-tools ? (https://github.com/erikd/sndfile-tools)

is the bg.png image in LoopTools folder?

**Comment by aleksia123** [comment]
Yes, I had the sndfile-tools installed. For some reason I couldnt get it to work. When I ran "sndfile-waveform -c -1 -S 0 click120.wav waveform.png" manually it opened up

im on linux mint on their latest debian edition. using Python 3.7.3 , issue resolved however, thanks.

**Comment by sonejostudios** [comment]
you are welcome, have fun with LoopTool! :)
